apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # For CRD
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-8.1/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-8.1/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-8.1/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml

  ## For snapshot-controller
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v8.0.1/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v8.0.1/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml

  # For VolumeSnapshotClass
  - volume_snapshot_class.yaml

images:
  - name: registry.k8s.io/sig-storage/snapshot-controller:v7.0.1
    newName: k8s.gcr.io/sig-storage/snapshot-controller
    newTag: v8.0.1
