name: test

on:
  push:

jobs:
  csi-sanity:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.15"

      - name: Run tests
        run: go test ./...
      - name: Run vetting/linting checks
        run: go vet ./...
